config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  get 'password_resets/new'
  get 'password_resets/create'
  get 'password_resets/edit'
  get 'password_resets/update'
  root 'static_pages#top'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  resources :password_resets, only: %i[new create edit update]
  resources :trees do
    resources :layers
  end
  resources :users
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
# frozen_string_literal: true

class Board < ApplicationRecord
  belongs_to :layer
end

app/models/layer.rb
# frozen_string_literal: true

class Layer < ApplicationRecord
  enum branch: { left: 0, left_down: 1, right: 2, right_down: 3 }
  belongs_to :tree
  belongs_to :user

  validates :parent_id, presence: true
  validates :positionX, presence: true
  validates :positionY, presence: true
end

app/models/tree.rb
# frozen_string_literal: true

class Tree < ApplicationRecord
  has_many :layers, dependent: :destroy
  belongs_to :user
  validates :title, presence: true, length_with_wide_char: { maximum: 20 }
  validates :description, length_with_wide_char: { maximum: 20 }

  enum state: { private_tree: 0, public_tree: 1 }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  authenticates_with_sorcery!
  has_many :layers, dependent: :destroy
  has_many :trees, dependent: :destroy
  validates :password, confirmation: true
  validates :email, presence: true, uniqueness: true
  validates :user_name, presence: true, uniqueness: true, length: { maximum: 10 }
  validates :reset_password_token, uniqueness: true, allow_nil: true
  def mine?(object)
    # 呼び出し元のオブジェクトのIDを示す self.id を省略した記法。
    # @user.mine?(object)のように利用すると、object.user_id と @user.id を比較する。
    object.user_id == id
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  add_flash_types :success, :info, :warning, :danger
  before_action :require_login

  private

  def not_authenticated
    redirect_to login_path, warning: 'Please login.'
  end
end

app/controllers/layers_controller.rb
# frozen_string_literal: true

class LayersController < ApplicationController
  protect_from_forgery
  before_action :set_layer, only: %i[show edit update destroy]
  skip_before_action :require_login, only: %i[index]
  def index
    tree = Tree.find(params[:tree_id])
    # 公開ツリー または ユーザがauthor
    if tree.state == 'public_tree' || current_user&.id == tree.user_id
      gon.layers = tree.layers.all.order(:layer_id)
      gon.current_user = current_user&.id
      @author = User.find(tree.user_id)
      gon.search = tree.layers.where('body like ?', "%#{params[:search]}%") if params[:search] != nil
    else
      redirect_back(fallback_location: trees_path)
    end
  end

  def show; end

  def create
    unless set_layer
      layer = Layer.new(layer_params)
      layer.save
    end
  end

  def update
    @layer.update(layer_params)
    redirect_to tree_layers_path
  end

  def destroy
    @layer.destroy
    redirect_to tree_layers_path
  end

  private

  def set_layer
    @layer = Layer.find_by(layer_id: params[:layer_id], user_id: params[:user_id], tree_id: params[:tree_id])
  end

  def layer_params
    params.permit(:id, :title, :body, :positionX, :positionY, :parent_id, :db_id, :layer_id, :user_id, :tree_id)
  end
end

app/controllers/password_resets_controller.rb
# frozen_string_literal: true

class PasswordResetsController < ApplicationController
  skip_before_action :require_login
  def new; end

  def create
    @user = User.find_by(email: params[:email])
    @user&.deliver_reset_password_instructions!
    redirect_to login_path, notice: 'I sent you an email.'
  end

  def edit
    @token = params[:id]
    @user = User.load_from_reset_password_token(@token)
    not_authenticated if @user.blank?
  end

  def update
    @token = params[:id]
    @user = User.load_from_reset_password_token(@token)

    return not_authenticated if @user.blank?

    @user.password_confirmation = params[:user][:password_confirmation]
    if @user.change_password(params[:user][:password])
      redirect_to login_path, notice: 'Update successful.'
    else
      flash.now[:notice] = 'Password does not match'
      render :edit
    end
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  skip_before_action :require_login, only: %i[top]
  def top; end
end

app/controllers/trees_controller.rb
# frozen_string_literal: true

class TreesController < ApplicationController
  before_action :set_tree, only: %i[edit update destroy]
  skip_before_action :require_login, only: %i[index]

  def index
    @q = Tree.ransack(params[:q])
    @trees = @q.result.order(:id).page(params[:page]).where(state: 'public_tree')
  end

  def new
    @tree = current_user.trees.new
  end

  def edit; end

  def create
    @tree = current_user.trees.new(set_tree_params)
    if @tree.save
      layer = current_user.layers.new(layer_id: 1, positionX: 500, positionY: 30, parent_id: 1,
                                      user_id: current_user.id, tree_id: @tree.id)
      layer.save!
      redirect_to tree_layers_path(@tree.id)
    else
      flash.now[:danger] = 'Create failure.Title and description are limited to 10 characters.'
      render :new
    end
  end

  def update
    if @tree.update(set_tree_params)
      redirect_to user_path, success: 'Update successful.' unless request.referer&.include?('layers')
    else
      flash[:danger] = 'Update failure.Title and description are limited to 10 characters.'
      render :new
    end
  end

  def destroy
    @tree.destroy
    redirect_to request.referer
  end

  private

  def set_tree_params
    params.require(:tree).permit(:id, :title, :description, :state, :leaf_count)
  end

  def set_tree
    @tree = current_user.trees.find(params[:id])
  end
end

app/controllers/user_sessions_controller.rb
# frozen_string_literal: true

class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new; end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_back_or_to root_path, success: 'Login successful.'
    else
      flash.now[:danger] = 'Login failed.'
      render :new
    end
  end

  def destroy
    logout
    redirect_to login_path, success: 'Logout successful.'
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[edit update destroy]
  skip_before_action :require_login, only: %i[new create]

  def index; end

  def new
    @user = User.new
  end

  def show
    @trees = current_user.trees.all.order(:id).page(params[:page])
  end

  def edit; end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to login_path, success: 'User was successfully created.'
    else
      flash.now[:danger] = 'User creation failed.'
      render :new
    end
  end

  def update
    @user.update(user_params)
    redirect_to user_path(current_user)
  end

  def destroy
    @user.destroy
    redirect_to root_path, success: 'Your account has been deleted.'
  end

  private

  def set_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :user_name)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/layers_helper.rb
# frozen_string_literal: true

module LayersHelper
end

app/helpers/password_resets_helper.rb
# frozen_string_literal: true

module PasswordResetsHelper
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
end

app/helpers/trees_helper.rb
# frozen_string_literal: true

module TreesHelper
end

app/helpers/user_sessions_helper.rb
# frozen_string_literal: true

module UserSessionsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layers/_search_form.html.erb
<%= search_form_for @q, url: url do |f| %>
    <%= f.search_field :title_or_body_cont, placeholder: 'search'%>
    <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UntangledPastaTrees</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
    <link rel="stylesheet" href="https://unpkg.com/easymde/dist/easymde.min.css">
    <script src="https://unpkg.com/easymde/dist/easymde.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Alegreya+Sans+SC:300" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= include_gon %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
      <%= render 'shared/header' %> 
    <% else %>
      <%= render 'shared/before_login_header' %>
    <% end %>
     <%= render 'shared/flash_message' %>
    <%= yield %>
  </body>
</html>

app/views/password_resets/create.html.erb
<h1>PasswordResets#create</h1>
<p>Find me in app/views/password_resets/create.html.erb</p>

app/views/password_resets/edit.html.erb
<div class="caption center">
  <h1>Password_reset</h1>
  <%= form_with model: @user, url: password_reset_path(@token), method: :put do |f| %>
    <%= f.label :email %>
    <%= @user.email %></br>
    <%= f.label :password %></br>
    <%= f.password_field :password, class: 'utext font-noto' %></br>
    <%= f.label :password_confirmation %></br>
    <%= f.password_field :password_confirmation, class: 'utext font-noto' %></br>
    <%= f.submit 'update', class: 'utext font' %>
  <% end %>
</div>

app/views/password_resets/new.html.erb
<div class="center">
  <h1>Find_your_email</h1>
  <%= form_with url: password_resets_path, local: true do |f| %>
    <%= f.label :email%>
    <%= f.text_field :email, class: "utext font-noto"%> 
    <%= f.submit 'submit', class: 'btn btn-primary utext font' %>
  <% end %>
</div>

app/views/password_resets/update.html.erb
<h1>PasswordResets#update</h1>
<p>Find me in app/views/password_resets/update.html.erb</p>

app/views/shared/_before_login_header.html.erb
<header>
  <div class="header-div">
    <%= link_to 'Login', login_path, id: 'log', class: "link-text" %>
    <%= link_to 'Top', root_path, id: "top", class: "link-text" %>
    <%= link_to 'All_trees', trees_path, id: "all-trees", class: "link-text" %>
  </div>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <% object.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_header.html.erb
<header>
  <div class="header-div">
    <%= link_to "user:#{current_user.user_name}", user_path(current_user),id: "my-page", class: "link-text" %>
    <%= link_to 'Logout', logout_path, id: "log", method: :delete, class: "link-text" %>
    <%= link_to 'Top', root_path, id: "top", class: "link-text" %>
    <%= link_to 'All_trees', trees_path, id: "all-trees", class: "link-text" %>
  </div>
</header>

app/views/shared/_tree.html.erb
<div class="card">
  <div class="title-text"><%= link_to tree.title, tree_layers_path(tree), data: {"turbolinks" => false}, :style => "color: black;" %></div>
  <div>Description:<%= tree.description %></div>
  <div>Author:<%= User.find(tree.user_id).user_name %></div>
  <div>Leaf:<%= tree.leaf_count %></div>
  <div>Updated_at:<%= l tree.updated_at, format: :long %></div>
  <% if current_user.id == tree.user_id %>
    <%= link_to "edit", edit_tree_path(tree), class: "card float-left" %>
    <% if tree.state == "public_tree" %>
      <%= link_to "public_tree", tree_path(tree, params: { tree: { state: "private_tree" }}), method: :patch, class: "card bg-green" %>
    <% elsif tree.state == "private_tree" %>
      <%= link_to "private_tree", tree_path(tree, params: { tree: { state: "public_tree"}}), method: :patch, class: "card" %>
    <% end %>
    <%= link_to "delete", tree_path(tree), class: "card float-right", method: :delete, data: { confirm: 'Are you sure you want to delete this tree?' } %>
  <% end %>
</div>

app/views/static_pages/top.html.erb
<div class="center">
  <div class="circle">
  <!--<img class="bgimage" src='https://gyazo.com/8f1a0854812d2efb856eeef514f6e646/raw'>-->
    <div class="inner"> <!-- 文字配置の基準となる親要素 -->
      <p class="text">Untangled pasta trees </p>
    </div>
  </div>
  <p style="color:red;">おしらせ:herokuの無料サービスの終了に伴い、2022年11月28日をもってこのサービスを終了または移転を計画しております。<br>本サービスをご利用の方は期日までにデータのバックアップをお願いします。</p>
  <%= link_to 'Create_tree',  new_tree_path, class: "caption link-text"%></br>
  <%= link_to 'All_trees', trees_path, class: "caption link-text"%></br>
  <%= link_to 'How_to_use', 'https://qiita.com/yoshidashota0328/private/dd67cbdb8ca7a7fd1d5f', class: "caption link-text"%>
</div>
<script>
$(function () {
  var availWidth = window.screen.width;
  const before = $('.text');
  const text = before.text(); // 文字をspanタグで囲む前のテキストを取得
  const textArray = text.split('');  // 取得したテキストを1文字ずつに分割し配列にして変数に格納
    
  let after = '';
  $.each(textArray,function(index,val){ // 配列の各文字をspanタグで囲み、繋げていく
    after += '<div class="move">' + val + "</div>";
  });  
    
  before.html(after);  // 元のテキストに生成したタグごと置き換え
    
  const textcnt = textArray.length;
  const circleR = ($('.circle').height()) / 2; // 円の半径
  const fontH = ($('.inner').height());
  const dist = circleR - fontH;
  const animTime = $('.text').css('animation-duration').slice(0, -1);  // アニメーション時間を取得し、「s」を切り捨て
    
  $('.move').each(function(index) {
    const num = index + 1;
    const radX = Math.sin(360 / textcnt * num * (Math.PI / 180)); // 文字の中心からのX軸方向の移動距離を計算
    const radY = Math.sin((90 - (360 / textcnt * num)) * (Math.PI / 180)); // 文字の中心からのY軸方向の移動距離（実際にはマイナス移動）を計算
    $(this).css({'transform': 'translate(' + dist * radX + 'px, ' + -(dist * radY) + 'px) rotateX(90deg) rotateY(' + 360 / textcnt * num + 'deg)', //1文字ずつ円形に等間隔で円形に配置
                'animation-delay': animTime / textcnt * num + 's', // 1文字ずつアニメーション開始時間を遅延
                  });  //
  });
  // 2つの値の間のランダムな整数を得る
  function getRandomInt(min, max) {
    min = Math.ceil(min);
    max = Math.floor(max);
    return Math.floor(Math.random() * (max - min) + min); //The maximum is exclusive and the minimum is inclusive
  }
  // アルファベットをランダムに１文字変数に代入する
  var particle = function particle() {
    // 生成する文字列の長さ
    var l = 1;

    // 生成する文字列に含める文字セット
    var c = "abcdefghijklmnopqrstuvwxyzABΓΔEZHΘIKΛMNΞOΠPΣTΥΦXΨΩ1234567890";

    var cl = c.length;
    var r = "";
    for(var i=0; i<l; i++){
      r += c[Math.floor(Math.random()*cl)];
    }
    var x = getRandomInt(0, availWidth)
    var size = getRandomInt(5, 15)
    $('body').append('<div class="particle" style="font-size: ' + size + 'px; left: ' + x + 'px;">' + r + '</div>')
  }
  var i = 1;
  var particleLoop = setInterval(function() {
    particle()
    i++;
    if(i > 400) clearInterval(particleLoop);  
  }, 50);

});
</script>

app/views/trees/_search_form.html.erb
<%= search_form_for @q, url: url do |f| %>
    <%= f.search_field :title_or_description_cont, placeholder: 'search', class: "search"%>
    <%= f.submit class: 'btn btn-primary font' %>
<% end %>

app/views/trees/_tree.html.erb
<div class="card">
  <div class="title-text"><%= link_to tree.title, tree_layers_path(tree), data: {"turbolinks" => false}, :style => "color: black;" %></div>
  <div>Description:<%= tree.description %></div>
  <div>Author:<%= User.find(tree.user_id).user_name %></div>
  <div>Leaf:<%= tree.leaf_count %></div>
  <div>Updated_at:<%= l tree.updated_at, format: :long %></div>
</div>

app/views/trees/edit.html.erb
<div class="caption center">
  <h1>Edit_tree</h1>
  <%= form_with model: @tree, local: true do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <%= f.label :title %></br>
    <%= f.text_field :title, class: "utext font-noto" %></br>
    <%= f.label :description %></br>
    <%= f.text_field :description, class: "utext font-noto" %></br>
    <%= f.submit 'edit', class: "utext font" %>
  <% end %> 
</div>

app/views/trees/index.html.erb
<div class="center">
  <h1>All_trees</h1>
  <%= render 'search_form', url: trees_path %>
  <% if @trees.present? %>
    <%= render @trees %>
  <% end %>
  <%= paginate @trees %>
</div>

app/views/trees/new.html.erb
<div class="caption center">
  <h1>new_tree</h1>
  <%= form_with model: @tree, local: true do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <%= f.label :title %></br>
    <%= f.text_field :title, class: "utext font-noto" %></br>
    <%= f.label :description %></br>
    <%= f.text_field :description, class: "utext font-noto" %></br>
    <%= f.submit 'create', class: "utext font" %>
  <% end %> 
</div>

app/views/user_sessions/new.html.erb
<div class="caption center">
  <h1>Login</h1>
  <%= form_with model: @user, local: true do |f| %>
    <%= f.label :email %></br>
    <%= f.text_field :email, class: "utext font-noto" %></br>
    <%= f.label :password %></br>
    <%= f.password_field :password, class: "utext font-noto" %></br>
    <%= f.submit 'login', class: "utext font" %>
  <% end %>
  <%= link_to 'Create_user', new_user_path, class: "link-text" %></br>
  <%= link_to ('Forgot_password?'), new_password_reset_path, class: "link-text" %>
</div>

app/views/users/edit.html.erb
<div class="caption center">
  <h1>Edit_user</h1>
  <%= form_with model: @user, local: true do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <%= f.label :email %></br>
    <%= f.text_field :email, class: "utext font-noto" %></br>
    <%= f.label :password %></br>
    <%= f.text_field :password, class: "utext font-noto" %></br>
    <%= f.submit 'edit', class: "utext font" %></br>
    <%= link_to "delete your account", user_path(@user), class: "card", method: :delete, data: { confirm: 'Are you sure you want to delete your account?' } %>
  <% end %> 
</div>

app/views/users/new.html.erb
<div class="caption center">
  <h1>Create_user</h1>
  <%= form_with model: @user, local: true do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <%= f.label :user_name %></br>
    <%= f.text_field :user_name, class: "utext font-noto" %></br>
    <%= f.label :email %></br>
    <%= f.text_field :email, class: "utext font-noto" %></br>
    <%= f.label :password %></br>
    <%= f.password_field :password, class: "utext font-noto" %></br>
    <%= f.label :password_confirmation %></br>
    <%= f.password_field :password_confirmation, class: "utext font-noto" %></br>
    <%= f.submit "create", class: "utext font" %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="center">
  <h1>My_trees</h1>
  <%= link_to 'Edit_user', edit_user_path, class: "link-text caption card" %></br>
  <% if @trees.present? %>
    <% @trees.each do |tree| %>
      <%= render partial: 'shared/tree', locals: { tree: tree } %>
    <% end %>
    <%= paginate @trees %>
  <% end %>
</div>